from typing import Any, Optional, Protocol

from constants import Action, State


class BaseAgent(Protocol):
    def choose_action(self, state: State) -> Action: ...
    def train(self, env: Any, num_episodes: int, suffix: Optional[str]) -> None: ...
    def save(self, filename: str) -> None: ...
    def load(self, filename: str) -> None: ...

    @classmethod
    def create(cls, enable_logging: bool) -> "BaseAgent": ...

    @property
    def requires_training(self) -> bool: ...
