from typing import Any, Protocol

from constants import Action, State


class BaseAgent(Protocol):
    def choose_action(self, state: State) -> Action: ...
    def train(self, env: Any, num_episodes: int) -> None: ...
    def save(self, filename: str) -> None: ...
    def load(self, filename: str) -> None: ...
